-- Check if all required columns exist, if not add them
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'Address')
BEGIN
    ALTER TABLE Venues ADD Address NVARCHAR(MAX) NOT NULL DEFAULT '';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'City')
BEGIN
    ALTER TABLE Venues ADD City NVARCHAR(MAX) NOT NULL DEFAULT '';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'HasStaggeredSeating')
BEGIN
    ALTER TABLE Venues ADD HasStaggeredSeating BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'HasWheelchairSpaces')
BEGIN
    ALTER TABLE Venues ADD HasWheelchairSpaces BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'LayoutType')
BEGIN
    ALTER TABLE Venues ADD LayoutType NVARCHAR(MAX) NOT NULL DEFAULT '';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'NumberOfRows')
BEGIN
    ALTER TABLE Venues ADD NumberOfRows INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'RowSpacing')
BEGIN
    ALTER TABLE Venues ADD RowSpacing INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'SeatSpacing')
BEGIN
    ALTER TABLE Venues ADD SeatSpacing INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'SeatsPerRow')
BEGIN
    ALTER TABLE Venues ADD SeatsPerRow INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Venues' AND COLUMN_NAME = 'WheelchairSpaces')
BEGIN
    ALTER TABLE Venues ADD WheelchairSpaces INT NOT NULL DEFAULT 0;
END

-- Mark migrations as applied
IF NOT EXISTS (SELECT 1 FROM __EFMigrationsHistory WHERE MigrationId = '20250706090450_UpdateVenueSchema')
BEGIN
    INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion)
    VALUES ('20250706090450_UpdateVenueSchema', '8.0.16');
END

IF NOT EXISTS (SELECT 1 FROM __EFMigrationsHistory WHERE MigrationId = '20250706102344_AddSeatReservationsAndFixPrecision')
BEGIN
    INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion)
    VALUES ('20250706102344_AddSeatReservationsAndFixPrecision', '8.0.16');
END
